# Generated by Django 5.2.15 on 2026-07-03 14:15

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=account.models.get_post_path)),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Likes')),
                ('comment_count', models.IntegerField(default=0, verbose_name='Коментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
